version: '3'

services:
  postgres1:
    image: postgres:16
    ports:
      - "5436:5436"
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    image: controltowerpt
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres1
    env_file:
      - .env

volumes:
  postgres_data:
