name: MainProtection

on:
  push:
    branches:
      - master
      - dev

  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Protect Main
        if: 1 != 2
        run: |
          echo "Main is protected"
          exit 1
