name: MainProtection

on:
  push:
    branches:
      - master
      - dev

  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Protect Main
        if: github.event_name == 'pull_request' && github.base_ref == 'master'
        run: |
          echo "Main is protected"
          exit 1
