name: CI

on:
  push:

  pull_request:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
            distribution: 'adopt'
            java-version: '21'
            cache: gradle

      - name: Setup Gradle 8.4
        uses: gradle/setup-gradle@v3
        with:
          gradle-version: 8.4

      - name : Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Run tests
        run: ./gradlew test

